import { ChecklistItem } from "../types";

export const CHECKLIST_ITEMS: ChecklistItem[] = [
  {
    id: "jwt-intro",
    category: "Setup",
    title: "1. Understanding JWT & Components",
    description: "Learn what a JSON Web Token is and inspect its three essential parts: Header, Payload, and Signature.",
    detailedGuide: "A JSON Web Token (JWT) is a compact, URL-safe means of representing claims to be transferred between two parties. JWTs consist of three parts separated by dots (header.payload.signature):\n\n• **Header**: Typically contains the signing algorithm (e.g., HS256) and token type ('JWT').\n• **Payload**: Contains the statements (claims) about an entity (e.g., user ID, username, roles).\n• **Signature**: Generated by hashing the encoded header, encoded payload, and your server secret key. It asserts that the sender is who they say they are and guarantees the token wasn't tampered with.\n\nUse the interactive Sandbox panel to inspect claims in real-time."
  },
  {
    id: "express-setup",
    category: "Setup",
    title: "2. Setting Up Express Application",
    description: "Initialize your Node.js workplace, initialize package config, and construct your core Express server.",
    codeSnippet: `const express = require('express');
const app = express();
const PORT = process.env.PORT || 3000;

app.use(express.json()); // Essential body-parser for incoming JSON body

app.listen(PORT, () => {
  console.log(\`Server is running on port\${PORT}\`);
});`,
    detailedGuide: "To begin building a standard backend application:\n1. Initialize npm config: `npm init -y` inside a terminal.\n2. Add the web framework: `npm install express --save`.\n3. Create your entry point file `app.js` or `server.ts`.\n\nMake sure to parse incoming JSON payloads using the Express built-in body-parser helper: `app.use(express.json())` so that credentials loaded via fetch requests are parsed successfully."
  },
  {
    id: "install-deps",
    category: "Setup",
    title: "3. Installing Security Dependencies",
    description: "Install cryptography tools and header handlers: jsonwebtoken, bcryptjs, configuration environments, and cookie-parser.",
    codeSnippet: `npm install jsonwebtoken bcryptjs cookie-parser dotenv`,
    detailedGuide: "Our JWT architecture relies on several trusted packages:\n\n• **jsonwebtoken**: To sign, decode, and verify access/refresh claims.\n• **bcryptjs**: Used to securely hash and salt user passwords on registration, and compare password entry hashes during sign-in.\n• **cookie-parser**: Extracts details from incoming HTTP Cookie headers and populates `req.cookies`.\n• **dotenv**: Loads secret keys safely from your `.env` workspace variables."
  },
  {
    id: "auth-endpoints",
    category: "Implementation",
    title: "4. Create Registration & Sign-In Paths",
    description: "Establish dedicated authentication router paths to safely process credentials, matching against user records.",
    codeSnippet: `const router = require('express').Router();
const bcrypt = require('bcryptjs');

// Router endpoints handles register input
router.post('/register', async (req, res) => {
  const { username, password } = req.body;
  // Hash password using bcrypt
  const salt = await bcrypt.genSalt(10);
  const passwordHash = await bcrypt.hashSync(password, salt);
  
  // Save user in persistent DB
  // ...
});`,
    detailedGuide: "You must establish dedicated API endpoints (`/register` and `/login`) inside Express router scripts.\n\n• **On Registration**: Extract details, run validation filters, verify that the username is unique, salt-hash the raw password using `bcrypt.genSalt(10)` and `bcrypt.hash()`, and store the hashed record in the database.\n• **On Login**: Search the database for the username. If found, compare the incoming password with the stored hash using `bcrypt.compare(password, storedHash)`. Reject invalid credentials with a uniform 401 Unauthorized status code to protect password leak details."
  },
  {
    id: "jwt-generation",
    category: "Implementation",
    title: "5. Digital Signing of JWT Credentials",
    description: "Compute secure Access and Refresh token strings containing specific subject claims, and sign with secret keys.",
    codeSnippet: `const jwt = require('jsonwebtoken');

// Generating Access Token
const accessToken = jwt.sign(
  { sub: user.id, username: user.username, role: 'User' },
  process.env.JWT_SECRET,
  { expiresIn: '15m' } // Short lived!
);`,
    detailedGuide: "Tokens are signed on the server using `jwt.sign(payload, secret, options)`:\n\n• Keep payloads concise (sub, username, permissions). Never store sensitive secrets like password hashes or credit card details inside, because JWTs are base64-encoded and fully visible to whoever accesses them!\n• Use highly distinct expiration margins for security. Access tokens should remain short-lived (e.g., 15 minutes) to protect against token leakage, while refresh tokens remain long-lived (e.g., 7 days)."
  },
  {
    id: "middleware-auth",
    category: "Implementation",
    title: "6. Building JWT Verification Middleware",
    description: "Develop reusable middleware that inspects Headers or Cookies (cookie-parser) to authorize API requests.",
    codeSnippet: `// Middleware structure inside server
function authenticateToken(req, res, next) {
  const token = req.cookies.access_token || req.headers['authorization']?.split(' ')[1];
  
  if (!token) return res.status(401).json({ error: 'Access token missing' });

  try {
    const verified = jwt.verify(token, process.env.JWT_SECRET);
    req.user = verified;
    next(); // Pass control to downstream handler
  } catch (err) {
    res.status(403).json({ error: 'Token is invalid or expired' });
  }
}`,
    detailedGuide: "To secure private resources, craft a reusable Express middleware function. This intercepts requests, extracts the JWT string, and validates it using `jwt.verify(token, secret)`.\n\nIf verification succeeds, append the decoded details directly to the request context (e.g., `req.user = decoded`) and call `next()`. If token extraction fails, return a 401 access challenge. If verification fails (due to key mismatch or expired token), halt the lifecycle with a 403 Forbidden error."
  },
  {
    id: "securing-routes",
    category: "Implementation",
    title: "7. Applying Middleware to Private Routes",
    description: "Lock down specific Express sub-paths by inserting the verification middleware ahead of request handlers.",
    codeSnippet: `// Securing specific workspace profiles
app.get('/api/profile', authenticateToken, (req, res) => {
  // Safe route: req.user contains sub details
  res.json({ data: 'Secure workspace access granted!' });
});`,
    detailedGuide: "Applying route guards in Express is seamless. Insert your custom `authenticateToken` middleware directly as an argument before the endpoint's final callback handler.\n\nUsing this technique, Express guarantees that the final function executes only after passing the middleware validation check. Any non-authenticated user receives proper HTTP errors with zero access to underlying data, maintaining secure system isolation."
  },
  {
    id: "cookie-storage",
    category: "Security",
    title: "8. Storing Tokens in HttpOnly Cookies",
    description: "Defeat Cross-Site Scripting (XSS) exposures by avoiding client localStorage and storing JWTs in cookies.",
    codeSnippet: `res.cookie('access_token', accessToken, {
  httpOnly: true,     // Block client JS reading! (Saves from XSS)
  secure: true,       // Requires HTTPS connection
  sameSite: 'lax',    // Mitigates CSRF exposures
  maxAge: 15 * 60 * 1000 // 15 minutes
});`,
    detailedGuide: "Storing JWTs in browser `localStorage` or `sessionStorage` leaves them vulnerable to Cross-Site Scripting (XSS) attacks. If an attacker injects a malicious script on your page, they can easily read everything in localStorage.\n\n**The Security Solution:** Store your JWTs inside standard HTTP response cookies using the **`httpOnly: true`** flag. This instructs the browser to never expose the cookie key via client-side JavaScript (`document.cookie`), completely preventing script thefts while maintaining automatic headers transmission."
  },
  {
    id: "token-refresh",
    category: "Security",
    title: "9. Refresh Token Rotation & Session Lifecycle",
    description: "Construct a sliding user session by validating Refresh Tokens and rotating short-lived Access Tokens.",
    codeSnippet: `app.post('/api/refresh', (req, res) => {
  const refreshToken = req.cookies.refresh_token;
  if (!refreshToken) return res.sendStatus(401);
  
  jwt.verify(refreshToken, process.env.JWT_REFRESH_SECRET, (err, user) => {
    if (err) return res.sendStatus(403);
    const newAccess = jwt.sign({ sub: user.sub, username: user.username }, process.env.JWT_SECRET, { expiresIn: '15m' });
    res.cookie('access_token', newAccess, { httpOnly: true });
    res.json({ accessToken: newAccessToken });
  });
});`,
    detailedGuide: "To preserve user convenience without risking perpetual token lifespan:\n\n1. At login, generate both **Access Token** (expires in minutes) and **Refresh Token** (expires in days).\n2. When client requests fail due to an expired Access Token, call the `/refresh` endpoint, providing the Refresh Token.\n3. Verify the Refresh Token using the separate `JWT_REFRESH_SECRET`. If valid, generate and return a brand new short-lived Access Token in a fresh cookie, maintaining absolute security and convenient session continuity."
  },
  {
    id: "exercises-checklist",
    category: "Exercises",
    title: "10. Mandatory Security Exercises",
    description: "Take on core security challenges to harden registration validation, manage profile sync, revoke tokens, and observe brute-force rate limits.",
    detailedGuide: "Confirm that every core security requirement is implemented in your sandbox database environment:\n\n• **Input Filter Validation**: Ensure password strength (>=6 chars) and username criteria are checked.\n• **Self profile update**: Edit and update profile fields dynamically via custom authenticated routes.\n• **Refresh Sign-Out Purge**: Invalidate and revoke refresh tokens on explicit sign-out by logging them on a server blacklist.\n• **Token Tamper Sandbox**: Try modifying the token contents to see verification mechanisms catch tampering instantly.\n• **Security Rate Limiting**: Limit authentication endpoint attempts to defend against dictionary and brute-force cracking attempts.\n• **Email Verification Simulation**: Secure registration with unique tokens that users must verify."
  }
];
